[workspace]
git_tag_enable=false
git_release_enable = false # disable GitHub/Gitea releases
pr_branch_prefix = "release-plz-" # PR branch prefix
pr_labels = ["release"] # add the `release` label to the release Pull Request
publish_timeout = "10m" # set a timeout for `cargo publish`

[[package]]
name = "git-stratum"
changelog_include = ["git-stratum"]
changelog_path = "CHANGELOG.md"
git_tag_name = "v{{ version }}"
git_tag_enable = true
git_release_enable = true
publish = true

# Keep this crate local for now as it's only used for testing.
[[package]]
name = "git-stratum-utils"
changelog_include = ["git-stratum-utils"]
changelog_path = "CHANGELOG.md"
git_release_enable = false
publish = false
